package static

var TestChar = '\u16a1'

var RunicAlphabet = map[rune][]string {
	'\u16a0': {"ELDER-FUTHARK", "FEHU", "FEOH", "FE", "F"},
	'\u16a1': {"V"},
	'\u16a2': {"ELDER-FUTHARK", "URUZ", "UR", "U"},
	'\u16a3': {"YR"},
	'\u16a4': {"Y"},
	'\u16a5': {"W"},
	'\u16a6': {"ELDER-FUTHARK", "THURISAZ", "THURS", "THORN"},
	'\u16a7': {"ETH"},
	'\u16a8': {"ELDER-FUTHARK", "ANSUZ", "A"},
	'\u16a9': {"OS", "O"},
	'\u16aa': {"AC", "A"},
	'\u16ab': {"AESC"},
	'\u16ac': {"LONG-BRANCH", "OSS", "O"},
	'\u16ad': {"SHORT-TWIG", "OSS", "O"},
	'\u16ae': {"O"},
	'\u16af': {"OE"},
	'\u16b0': {"ON"},
	'\u16b1': {"ELDER-FUTHARK", "RAIDO", "RAD", "REID", "R"},
	'\u16b2': {"ELDER-FUTHARK", "KAUNA"},
	'\u16b3': {"CEN"},
	'\u16b4': {"KAUN", "K"},
	'\u16b5': {"G"},
	'\u16b6': {"ENG"},
	'\u16b7': {"ELDER-FUTHARK", "GEBO", "GYFU", "G"},
	'\u16b8': {"GAR"},
	'\u16b9': {"ELDER-FUTHARK", "WUNJO", "WYNN", "W"},
	'\u16ba': {"ELDER-FUTHARK", "HAGLAZ", "H"},
	'\u16bb': {"HAEGL", "H"},
	'\u16bc': {"LONG-BRANCH", "HAGALL", "H"},
	'\u16bd': {"SHORT-TWIG", "HAGALL", "H"},
	'\u16be': {"ELDER-FUTHARK", "NAUDIZ", "NYD", "NAUD", "N"},
	'\u16bf': {"SHORT-TWIG", "NAUD", "N"},
	'\u16c0': {"DOTTED", "N"},
	'\u16c1': {"ELDER-FUTHARK", "ISAZ", "IS", "ISS", "I"},
	'\u16c2': {"E"},
	'\u16c3': {"ELDER-FUTHARK", "JERAN", "J"},
	'\u16c4': {"GER"},
	'\u16c5': {"LONG-BRANCH", "AR", "AE"},
	'\u16c6': {"SHORT-TWIG", "AR", "A"},
	'\u16c7': {"ELDER-FUTHARK", "IWAZ", "EOH"},
	'\u16c8': {"ELDER-FUTHARK", "PERTHO", "PEORTH", "P"},
	'\u16c9': {"ELDER-FUTHARK", "ALGIZ", "EOLHX"},
	'\u16ca': {"ELDER-FUTHARK", "SOWILO", "S"},
	'\u16cb': {"SIGEL", "LONG-BRANCH", "SOL", "S"},
	'\u16cc': {"SHORT-TWIG", "SOL", "S"},
	'\u16cd': {"C"},
	'\u16ce': {"Z"},
	'\u16cf': {"ELDER-FUTHARK", "TIWAZ", "TIR", "TYR", "T"},
	'\u16d0': {"SHORT-TWIG", "TYR", "T"},
	'\u16d1': {"D"},
	'\u16d2': {"ELDER-FUTHARK", "BERKANAN", "BEORC", "BJARKAN", "B"},
	'\u16d3': {"SHORT-TWIG", "BJARKAN", "B"},
	'\u16d4': {"DOTTED", "P"},
	'\u16d5': {"OPEN-P"},
	'\u16d6': {"ELDER-FUTHARK", "EHWAZ", "EH", "E"},
	'\u16d7': {"ELDER-FUTHARK", "MANNAZ", "MAN", "M"},
	'\u16d8': {"LONG-BRANCH", "MADR", "M"},
	'\u16d9': {"SHORT-TWIG", "MADR", "M"},
	'\u16da': {"ELDER-FUTHARK", "LAUKAZ", "LAGU", "LOGR", "L"},
	'\u16db': {"DOTTED", "L"},
	'\u16dc': {"ELDER-FUTHARK", "INGWAZ"},
	'\u16dd': {"ING"},
	'\u16de': {"ELDER-FUTHARK", "DAGAZ", "DAEG", "D"},
	'\u16df': {"ELDER-FUTHARK", "OTHALAN", "ETHEL", "O"},
	'\u16e0': {"EAR"},
	'\u16e1': {"IOR"},
	'\u16e2': {"CWEORTH"},
	'\u16e3': {"CALC"},
	'\u16e4': {"CEALC"},
	'\u16e5': {"STAN"},
	'\u16e6': {"LONG-BRANCH", "YR"},
	'\u16e7': {"SHORT-TWIG", "YR"},
	'\u16e8': {"ICELANDIC", "YR"},
	'\u16e9': {"Q"},
	'\u16ea': {"X"},
	'\u16eb': {"SINGLE", "PUNCTUATION"},
	'\u16ec': {"MULTIPLE", "PUNCTUATION"},
	'\u16ed': {"CROSS", "PUNCTUATION"},
	'\u16ee': {"GOLDEN-NUMBER", "17", "ARLAUG"},
	'\u16ef': {"GOLDEN-NUMBER", "18", "TVIMADUR"},
	'\u16f0': {"GOLDEN-NUMBER", "19", "BELGTHOR"},
	'\u16f1': {"TOLKEIN", "K"},
	'\u16f2': {"TOLKEIN", "SH"},
	'\u16f3': {"TOLKEIN", "OO"},
	'\u16f4': {"FRANKS-CASKET", "OS"},
	'\u16f5': {"FRANKS-CASKET", "IS"},
	'\u16f6': {"FRANKS-CASKET", "EH"},
	'\u16f7': {"FRANKS-CASKET", "AC"},
	'\u16f8': {"FRANKS-CASKET", "AESC"},
}